Npred: 10

Q: [[15, 0, 0, 0, 0, 0],
    [0, 15, 0, 0, 0, 0],
    [0, 0, 50, 0, 0, 0],
    [0, 0, 0, 5, 0, 0],
    [0, 0, 0, 0, 5, 0],
    [0, 0, 0, 0, 0, 5]]

R: [[0.6, 0, 0],
    [0, 0.6, 0],
    [0, 0, 0.75]]

#### 

Npred_to : 10

Qto: [[5, 0, 0, 0, 0, 0],
      [0, 5, 0, 0, 0, 0],
      [0, 0, 30, 0, 0, 0],
      [0, 0, 0, 5, 0, 0],
      [0, 0, 0, 0, 5, 0],
      [0, 0, 0, 0, 0, 5]]

Rto: [[0.6, 0, 0],
      [0, 0.6, 0],
      [0, 0, 0.75]]

Theta: [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]

rmin: 0.2

spline_deg: 3

n_ctrl_pts: 5