simid: 4

uris:
# - radio://0/80/2M/E7E7E7E7E1
- radio://0/80/2M/E7E7E7E7E7
# - radio://0/80/2M/E7E7E7E7E2
# - radio://0/80/2M/E7E7E7E7E3
# - radio://0/80/2M/E7E7E7E7E9

drone_bodies:
# - DroneE1
# - DroneE7
- DroneEE7
# - DroneE2
# - DroneE3
# - DroneE9

mass:
# E1
- 34.09
# E2
- 31.06
# E3
- 32.85
# E9
# - 32.06

Ts: 0.1

Tsim: 10

T_coeff:
- 1
- 1
- 1
# - 0

alpha:
- 1.0
- 1.0
- 1.0
# - 1.0

PWM0:
# E1
- 40000
# E2
- 40872
# E3
- 42420
# E9
- 40640

bias:
- [0.0,0.0]
- [0.0,0.0]
- [0.0,-0.0]
- [-0.0,0.0]