simid: 3

uris:
- udp://0.0.0.0:19850
# - udp://0.0.0.0:19851
# - udp://0.0.0.0:19852
# - udp://0.0.0.0:19853

drone_bodies:
- crazyflie_1
# - crazyflie_2
# - crazyflie_3
# - crazyflie_4
# - crazyflie_5
# - crazyflie_6
# - crazyflie_7

mass:
# E1
- 34.09
# E2
- 31.06
# E3
- 32.85
# E9
- 32.06

Ts: 0.1

Tsim: 30

T_coeff:
- 1
- 1
- 1
- 1

alpha:
- 1.0
- 1.0
- 1.0
- 1.0

PWM0:
# E1
# - 38734
- 40000
# E2
# - 38734
- 40000
# E3
# - 38734
- 40000
# E9
# - 38734
- 40000

bias:
- [0.0,0.0]
- [0.0,0.0]
- [0.0,-0.0]
- [-0.0,0.0]